services:
  # Serviço da sua aplicação Python/FastAPI
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    container_name: api
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual (código-fonte) dentro do contêiner no diretório /app
    # Isso permite que as alterações no código sejam refletidas instantaneamente (hot-reloading)
    volumes:
      - .:/app